network:
  proxy:
    clash:
      hostname: 127.0.0.1
      port: 7890
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ai_master?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    #RRTrjpH64fPC