server:
  port: 8899
  servlet:
    context-path: "/"
logging:
  level:
    org.springframework.web: DEBUG
    org.thymeleaf: DEBUG
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启SQL语句打印
  mapper-locations: classpath:mapper/*Mapper.xml
  #  数据库支持id唯一
  global-config:
    id-type: ASSIGN_ID
    capital-mode: false